// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6jo0DUGrJPHd3VWagTWmo-4s9cGns5P0',
    appId: '1:35290203803:android:cfb23f9986afc3eb52683e',
    messagingSenderId: '35290203803',
    projectId: 'todo-app-af61b',
    storageBucket: 'todo-app-af61b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5oENcGNAF4j5ealm_fCenaI9eeI0QPGQ',
    appId: '1:35290203803:ios:ca2e090d0ad9995852683e',
    messagingSenderId: '35290203803',
    projectId: 'todo-app-af61b',
    storageBucket: 'todo-app-af61b.appspot.com',
    iosClientId: '35290203803-op9ffege3e3j3ts9ouqi8dffgr4kilou.apps.googleusercontent.com',
    iosBundleId: 'com.app.todolist',
  );
}
